version: '3'
services:
  webserver:
    container_name: web
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - "./devops/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./devops/nginx/conf.d:/etc/nginx/conf.d"
      - "./:/var/www/html"
    links:
      - main
    networks:
      - mynet
    command: [nginx-debug, '-g', 'daemon off;']

  main:
    build:
      context: ./devops/php
    ports:
      - "9000:9000"
    container_name: php
    volumes:
      - "./:/var/www/html"
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
