version: '3'
services:
  web-ml:
    container_name: web-ml
    image: nginx
    ports:
      - "8881:80"
    volumes:
      - "./devops/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./devops/nginx/conf.d:/etc/nginx/conf.d"
      - "./:/var/www/html"
    links:
      - php-ml
    networks:
      - mlnet
    command: [nginx-debug, '-g', 'daemon off;']

  php-ml:
    build:
      context: ./devops/php
    ports:
      - "9000:9000"
    container_name: php-ml
    volumes:
      - "./:/var/www/html"
    networks:
      - mlnet
networks:
  mlnet:
    driver: bridge
